name: Deploy Frontend to Jooper Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # or your preferred version

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Copy dist folder to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.JOOPER_SSH_KEY }}
          source: "dist/*"
          target: "~/apps/ai-chatbot-frontend/dist"

      - name: Run remote deployment commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.JOOPER_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/ai-chatbot-frontend/*
            sudo mv ~/apps/ai-chatbot-frontend/dist/* /var/www/ai-chatbot-frontend/
            sudo chown -R www-data:www-data /var/www/ai-chatbot-frontend/
            sudo chmod -R 755 /var/www/ai-chatbot-frontend/
            sudo systemctl restart nginx
            echo "Deployment completed successfully!"