name: Deploy Frontend to Jooper Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy source code to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.JOOPER_SSH_KEY }}
          source: "."
          target: "/root/apps/ai-chatbot-frontend"

      - name: Build and deploy on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.JOOPER_SSH_KEY }}
          script: |
            cd /root/apps/ai-chatbot-frontend
            git pull origin main
            npm install
            npm run build
            sudo rm -rf /var/www/ai-chatbot-frontend/*
            sudo mv ~/apps/ai-chatbot-frontend/dist/* /var/www/ai-chatbot-frontend/
            sudo chown -R www-data:www-data /var/www/ai-chatbot-frontend/
            sudo chmod -R 755 /var/www/ai-chatbot-frontend/
            sudo systemctl restart nginx
            echo "Deployment completed successfully!"